server:
  port: ${SERVER_PORT:8010}
  servlet:
    context-path: /api-listen/v1
    
grpc:
  client:
    grpc-server:
      address: localhost:8211
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      permitKeepAliveWithoutCalls: true
      keepAliveTime: ${GRPC_KEEP_ALIVE_TIME:60}
      keepAliveTimeout: ${GRPC_KEEP_ALIVE_TIMEOUT:20}
      negotiationType: PLAINTEXT

logging:
  file: api-speak.log
  level:
    root: ${LOGGING_LEVEL:info}
